sudo: required
langauge: generic
services:
  - docker

before_install:
  - docker build -t phrbshrp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true phrbshrp/docker-react npm run test
